version: "2.1"
volumes: 
    resin-data:
services:
  lunchbox:
    image: lunchboxlambda/lunchbox:1.2.2
    devices:
      - /dev/ttyUSB0:/dev/controller
    ports:
      - 80:80
    volumes:
      - resin-data:/data
    restart: always
