version: "2.1"
volumes: 
    resin-data:
services:
  lunchbox:
    image: lunchboxlambda/brain:1.1.1
    devices:
      - /dev/ttyUSB0:/dev/controller
    ports:
      - 2280:80
    volumes:
      - resin-data:/data
    restart: no
